version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: agent-secrets
    binary: agent-secrets
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/omriashke/agent-secrets-cli/cmd.Version={{.Version}}

archives:
  - id: agent-secrets
    format: binary
    name_template: "agent-secrets_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: omriashke
    name: agent-secrets-cli
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
